---

- name: Debian/Ubuntu | Install apt-transport-https lsb-release gnupg2 and ca-certificates
  apt:
    name:
      - apt-transport-https
      - lsb-release
      - gnupg2
    state: present

- name: Debian/Ubuntu | Installing Wazuh repository key (Ubuntu 14)
  become: true
  shell: |
    set -o pipefail
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
  args:
    warn: false
    executable: /bin/bash


- name: Adding Wazuh repo
  apt_repository:
   repo: deb https://packages.wazuh.com/3.x/apt/ stable main
   state: present

- name: Debian/Ubuntu | Install wazuh-manager
  apt:
    name:
      - wazuh-manager
    state: present

# api de Wazuh

- name: Install Nodejs                       
  apt:
    name:
      - nodejs       
    state: present

- name: Install Wazuh-API
  apt:
    name:
      - wazuh-api    
    state: present

