
---
- hosts: localhost
  vars:
    - server_hostname: ca_wazuh
    - key_size: 4096
    - passphrase: # Set if you want passphrase
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: KE
    - email_address: wazuh@amor.com
    - organization_name: WazuhAmor
  tasks:
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "/var/ossec/api/configuration/ssl/{{ server_hostname }}_privkey.pem"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
   

    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "/var/ossec/api/configuration/ssl/{{ server_hostname }}.csr"
        privatekey_path: "/var/ossec/api/configuration/ssl/{{ server_hostname }}_privkey.pem"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ server_hostname }}"

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "/var/ossec/api/configuration/ssl/{{ server_hostname }}_cert.pem"
        privatekey_path: "/var/ossec/api/configuration/ssl/{{ server_hostname }}_privkey.pem"
        csr_path: "/var/ossec/api/configuration/ssl/{{ server_hostname }}.csr"
        provider: selfsigned

    
    - name: key
      lineinfile:
       destfile: /var/ossec/api/configuration/config.js
       regexp: 'config.https_key = "configuration/ssl/server.key"'
       line: 'config.https_key = "configuration/ssl/ca_wazuh_privkey.pem"'

    - name: cert
      lineinfile:
       destfile: /var/ossec/api/configuration/config.js
       regexp: 'config.https_cert = "configuration/ssl/server.crt"'
       line: 'config.https_cert = "configuration/ssl/ca_wazuh_cert.pem"'

    - name: user ca
      lineinfile:
       destfile: /var/ossec/api/configuration/config.js
       regexp: 'config.https_use_ca = "no"'
       line: 'config.https_use_ca = "yes"'


    - name: ca
      lineinfile:
       destfile: /var/ossec/api/configuration/config.js
       regexp: 'config.https_ca = "configuration/ssl/ca.crt"'
       line: 'config.https_ca = "configuration/ssl/ca_wazuh.csr"'



    - name: restart wazuh-manager
      service:
       name: wazuh-manager
       state: restarted

    - name: restart wazuh-api
      service:
       name: wazuh-api
       state: restarted

    - name: restart kibana    
      service:
       name: kibana   
       state: restarted


